heat_template_version: 2016-10-14

description: Template for keypairs

parameters:
  name:
    type: string
    label: Key pairs
    description: Generate keypairs

resources:
  generated_key_pair:
    type: OS::Nova::KeyPair
    properties:
      name: {get_param: name}
      save_private_key: True

outputs:
  private_key:
    description: Private key
    value: { get_attr: [ generated_key_pair, private_key ] }